name: Build P2 Site

env:
  TARGET: '2023-09-java17'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  DEPLOY_SECRET: ${{ secrets.SSH_PRIVATE_KEY_ED25519_BASE64 }}

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Build Image
      run: docker pull ghcr.io/elexis/docker-build:${{ env.TARGET }}
    - name: Build with Docker
      run:  docker run --rm --init -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven ghcr.io/elexis/docker-build:${{ env.TARGET }} xvfb-run mvn -V clean verify -B
